services:
  - type: web
    name: lotto-checker-server
    env: docker
    buildCommand: ""
    startCommand: python app.py
    plan: free
    region: frankfurt
    envVars:
      - key: FLASK_ENV
        value: production
    autoDeploy: true
